name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu cần

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Authenticate with Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set up database
      run: |
        docker compose -f docker-compose.yml build mysql
        docker compose -f docker-compose.yml build phpmyadmin

    - name: Build back-end application image
      run: docker compose -f docker-compose.yml build student-backend

    - name: Build front-end application image
      run: docker compose -f docker-compose.yml build student-frontend

    - name: Push images to Docker Hub
      run: docker compose -f docker-compose.yml push

    - name: Clean and Deploy to Dev Environment
      run: |
        docker images
        docker compose -f docker-compose.yml down -v
        yes | docker container prune
        docker compose -f docker-compose.yml up -d
        docker network ls
        docker volume ls

    - name: Clean up
      run: docker logout
