name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

      - name: Deploy to Dev Environment
        run: |
          docker-compose -f docker-compose.yml down -v
          docker container prune -f
          docker-compose -f docker-compose.yml up -d

      - name: Clean Up
        run: |
          docker logout
          docker network ls
          docker volume ls
          docker images

      - name: Check Deployment Status
        run: |
          # Check the status as needed
