name: CD Pipeline

#on:
 # workflow_run:
 #   workflows: ["CI Pipeline"]  # Chỉnh sửa tên workflow CI Pipeline thành "CI Pipeline"
#    types:
#      - completed
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Đảm bảo các submodule được checkout cùng với repository chính

    - name: Set up submodule
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

   
    - name: Clean and Deploy to AWS Environment
      run: |
        sudo docker images
        sudo docker compose -f docker-compose.yml down -v
        yes | docker container prune
        sudo docker compose -f docker-compose.yml up -d
        sudo docker compose ps
        sudo docke network ls
        sudo docker volume ls

    - name: Clean up
      run: docker logout
