name: CD Pipeline

#on:
 # workflow_run:
 #   workflows: ["CI Pipeline"]  # Chỉnh sửa tên workflow CI Pipeline thành "CI Pipeline"
#    types:
#      - completed
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Đảm bảo các submodule được checkout cùng với repository chính

    - name: Set up submodule
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive

    
    - name: Set up database
      run: |
        docker compose -f docker-compose.yml build mysql
        docker compose -f docker-compose.yml build phpmyadmin

  
    - name: Build back-end application image
      run: |
        cp student-backend/Dockerfile .
        docker compose -f docker-compose.yml build student-backend

    - name: Build front-end application image
      run: |
        cp student-backend/Dockerfile .
        docker compose -f docker-compose.yml build student-frontend

   
    - name: Clean and Deploy to Dev Environment
      run: |
        docker images
        docker compose -f docker-compose.yml down -v
        yes | docker container prune
        docker compose -f docker-compose.yml up -d
        docker compose ps
        docker network ls
        docker volume ls

    - name: Clean up
      run: docker logout
