# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages


on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Create index.html
        run: echo "<h1>Hello, world!</h1>" > ./_site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Authenticate with Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Run MySQL container
        run: |
          docker run -d --name mysql-container -p 3307:3306 -e MYSQL_DATABASE=studentdb -e MYSQL_USER=chucthien03 -e MYSQL_PASSWORD=chucthien03 -e MYSQL_ROOT_PASSWORD=chucthien03_root mysql:8.3.0

      - name: Run PHPMyAdmin container
        run: |
          docker run -d --name phpmyadmin-container -p 81:80 --link mysql-container:db -e PMA_HOST=db -e MYSQL_ROOT_PASSWORD=chucthien03_root phpmyadmin:latest

      - name: Run backend container
        run: |
          docker run -d --name student-backend -p 8081:8080 --link mysql-container:mysql-container chucthien03/student-backend
          
      - name: Run frontend container
        run: |
          docker run -d --name student-frontend -p 3001:3000 chucthien03/student-frontend

      - name: Wait for containers to start
        run: sleep 10

      - name: Show running containers
        run: docker ps -a

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: _site

 
