# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages


on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: docker compoose    
        run: |
          docker images
          docker compose -f docker-compose.yml down -v
          yes | docker container prune
          docker compose -f docker-compose.yml up -d
          docker network ls
          docker volume ls
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: _site

 
