name: 'Submodules Sync'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git config --global user.name 'ThienNoob'
          git config --global user.email '102866314+ThienNoob@users.noreply.github.com'
          git submodule update --init --recursive
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git remote set-url origin https://github.com/ThienNoob/student.git
          git commit -am "Auto updated submodule references" && git push origin main || echo "No changes to commit"
